all:
  sf_zend_mail:
    #framework_location:                         /usr/local/zend/share/ZendFramework/library/Zend
    config:                            
      charset: utf-8                             # charset to use : utf-8, iso-8859-1, ...
      encoding: quoted-printable                 # 7bit, 8bit, quoted-printable, base64 (default : quoted-printable)
      #transport:                                 # define which transport class to used, one or the other not both
        # sample with Sendmail
        #class: Zend_Mail_Transport_Sendmail      # Zend_Mail_Transport_Sendmail | Zend_Mail_Transport_Smtp
        #parameters: "-ffrom@yourdomain.com"
        
        # sample with Smtp
        #class: Zend_Mail_Transport_Smtp          # Zend_Mail_Transport_Sendmail | Zend_Mail_Transport_Smtp
        #parameters: 
          #- 127.0.0.1          # url or IP of the smtp server
          #- { auth: Plain|Crammd5|Login, username: yourusername, password: yourpassword }  #if required, else don't set
          
      decorator:                                 # define the layout use in the mail
        enabled: off                             # on | off : set true if all your mail share the same layout
        directory: "%SF_APP_TEMPLATE_DIR%"       # where the layout is located, ie %SF_APP_TEMPLATE_DIR%
        template: email                          # name of the layout, automatically translate to name.FORMAT.php
      view:                                      # define the view class used to render the template
        class: sfZendMailView